# -*- coding: utf-8 -*-
"""case_study-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hQh-zC3DnqgjbKNph7LQtbOwTDFn-gwW
"""

import pandas as pd
data = {
    'Student': ['S1', 'S2', 'S3', 'S4','S5','S6','S7','S8','S9','S10'],
    'Study Hours': [2, 3, 4, 5, 6, 7, 8, 4, 6, 9],
    'Attendance': [65, 70, 75, 80, 85, 90, 92, 78, 88, 95],
    'Assignment_Score': [55,60,65,72,78,85,88,70,80,92],
    'Previous_Score': [58,62,68,70,76,82,86,72,79,90],
    'Final_Score': [60,64,70,75,82,88,91,74,84,94]
}
df = pd.DataFrame(data)
print("\nDataFrame:")
print(df)

print(df)

for column in df.columns:
  if df[column].dtype !="object":
    print(column, "=",df[column].mean())

print(df.dtypes)

print(df.head(5))

print(df.tail(5))

print(df.info)

averages = df[['Study Hours', 'Attendance', 'Assignment_Score', 'Previous_Score', 'Final_Score']].mean()
print(averages)

print(df)

highest_scoring_student = df[df['Final_Score'] == df['Final_Score'].max()]
print(highest_scoring_student)

lowest_scoring_student = df[df['Final_Score'] == df['Final_Score'].min()]
print(lowest_scoring_student)

print(df[df['Attendance'] > 80])

print(df[df['Final_Score']>80])

print(df.describe())

import numpy as np
Final_Score_arr = df['Final_Score'].to_numpy()
mean_val = np.mean(Final_Score_arr)
print(mean_val)

Final_Score_arr=df['Final_Score'].to_numpy()
median=np.median(Final_Score_arr)
print(median)

Final_Score_arr=df['Final_Score'].to_numpy()
max_val=np.max(Final_Score_arr)
print(max_val)

Final_Score_arr=df['Final_Score'].to_numpy()
min_val=np.min(Final_Score_arr)
print(min_val)

Final_Score_arr=df['Final_Score'].to_numpy()
std_dev=np.std(Final_Score_arr)
print(std_dev)

import matplotlib.pyplot as plt
import numpy as np
data = [(np.float64(1.0), np.float64(55.5)), (np.float64(2.0), np.float64(57.6)),
        (np.float64(3.0), np.float64(63.9)), (np.float64(3.5), np.float64(68.6)),
        (np.float64(4.0), np.float64(65.3)), (np.float64(5.0), np.float64(69.3)),
        (np.float64(5.5), np.float64(76.7)), (np.float64(6.0), np.float64(76.3)),
        (np.float64(7.0), np.float64(76.6)), (np.float64(8.0), np.float64(83.6)),
        (np.float64(9.0), np.float64(84.6)), (np.float64(10.0), np.float64(88.6))]
hours, scores = zip(*data)
x = np.array(hours)
y = np.array(scores)
plt.figure(figsize=(8, 5))
plt.scatter(x, y, color='blue', label='Student Data', zorder=5)
m, c = np.polyfit(x, y, 1)
plt.plot(x, m*x + c, color='red', linestyle='--', label=f'Trendline (y = {m:.2f}x + {c:.2f})')
plt.title('Impact of Study Hours on Final Exam Scores')
plt.xlabel('Study Hours')
plt.ylabel('Final Score (%)')
plt.grid(True, linestyle=':', alpha=0.6)
plt.legend()
plt.show()

import matplotlib.pyplot as plt
import numpy as np
data = [(60, 69.5), (65, 70.3), (70, 75.4), (72, 79.2), (75, 75.5),
        (80, 78.3), (83, 85.4), (85, 84.1), (90, 83.1), (92, 87.2),
        (95, 85.9), (98, 87.5), (100, 90.7)]
attendance, scores = zip(*data)
x = np.array(attendance)
y = np.array(scores)
plt.figure(figsize=(8, 5))
plt.scatter(x, y, color='darkgreen', label='Student Attendance', zorder=5)
m, c = np.polyfit(x, y, 1)
plt.plot(x, m*x + c, color='orange', linestyle='--', label=f'Trendline (y = {m:.2f}x + {c:.2f})')
plt.title('Impact of Attendance Rate on Final Exam Scores')
plt.xlabel('Attendance Rate (%)')
plt.ylabel('Final Score (%)')
plt.xlim(55, 105)
plt.ylim(60, 95)
plt.grid(True, linestyle=':', alpha=0.6)
plt.legend()
plt.show()

import matplotlib.pyplot as plt
import numpy as np
scores = [69.5, 70.3, 75.4, 79.2, 75.5, 78.3, 85.4, 84.1, 83.1, 87.2, 85.9, 87.5, 90.7]
plt.figure(figsize=(8, 5))
bins = np.arange(65, 100, 5)
plt.hist(scores, bins=bins, color='steelblue', edgecolor='black', alpha=0.8, rwidth=0.9)
plt.title('Distribution of Final Exam Scores', fontsize=14, pad=15)
plt.xlabel('Final Score (%)', fontsize=12)
plt.ylabel('Number of Students (Frequency)', fontsize=12)
plt.xticks(bins)
plt.grid(axis='y', linestyle=':', alpha=0.6)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
students = [f"Student {i}" for i in range(1, 14)]
scores = [69.5, 70.3, 75.4, 79.2, 75.5, 78.3, 85.4, 84.1, 83.1, 87.2, 85.9, 87.5, 90.7]
colors = []
for score in scores:
    if score == max(scores):
        colors.append('darkgreen')
    elif score == min(scores):
        colors.append('firebrick')
    else:
        colors.append('skyblue')
plt.figure(figsize=(10, 5))
bars = plt.bar(students, scores, color=colors, edgecolor='black', alpha=0.85)
plt.title('Individual Student Final Exam Scores', fontsize=14, pad=15)
plt.xlabel('Students', fontsize=12)
plt.ylabel('Final Score (%)', fontsize=12)
plt.ylim(0, 100)
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle=':', alpha=0.6)
from matplotlib.patches import Patch
legend_elements = [
    Patch(facecolor='darkgreen', edgecolor='black', label=f'Highest Score ({max(scores)}%)'),
    Patch(facecolor='firebrick', edgecolor='black', label=f'Lowest Score ({min(scores)}%)'),
    Patch(facecolor='skyblue', edgecolor='black', label='Regular Score')
]
plt.legend(handles=legend_elements, loc='upper left')

plt.tight_layout()
plt.show()

import numpy as np
X = np.array([
    [2, 65, 55],
    [4, 75, 68],
    [6, 82, 74],
    [3, 70, 60],
    [8, 95, 88],
    [5, 80, 72],
    [7, 88, 81],
    [1, 60, 50],
    [9, 98, 92],
    [6, 85, 79]
])
print("Matrix X:\n", X)

print("\nMatrix Shape:", X.shape)

X_transpose = X.T

print("Shape of X_transpose:", X_transpose.shape)

import numpy as np
XTX = X.T @ X

print("Shape of XᵀX:", XTX.shape)
print("\nMatrix XᵀX:\n", XTX)

import numpy as np
study_hours = np.array([1.0, 2.0, 3.0, 3.5, 4.0, 5.0, 5.5, 6.0, 7.0, 8.0, 9.0, 10.0])
final_scores = np.array([55.5, 57.6, 63.9, 68.6, 65.3, 69.3, 76.7, 76.3, 76.6, 83.6, 84.6, 88.6])
dot_product = np.dot(study_hours, final_scores)
print("Dot Product:", dot_product)

import sympy as sp
x = sp.Symbol('x')
F = 40 + 5*x - 0.2*x**2
dF_dx = sp.diff(F, x)
print("Function F(x)   :", F)
print("Derivative dF/dx:", dF_dx)

import sympy as sp
x = sp.Symbol('x')
F = 40 + 5*x - 0.2*x**2
F_prime = sp.diff(F, x)
target_expression = 5 - 0.4*x
is_equal = sp.simplify(F_prime - target_expression) == 0
print(f"Calculated F'(x): {F_prime}")
print(f"Target Expression: {target_expression}")
print(f"Does F'(x) mathematically equal the target? {is_equal}")

import sympy as sp
x = sp.Symbol('x')
F_prime = 5 - 0.4*x
critical_point = sp.solve(F_prime, x)
print(f"The value of x for which F'(x) = 0 is: {critical_point[0]} hours")

import sympy as sp
import numpy as np
x_sym = sp.Symbol('x')
F_sym = 40 + 5*x_sym - 0.2*x_sym**2
max_score = F_sym.subs(x_sym, 12.5)
print(f"1. Peak Performance: At 12.5 study hours, the maximum score is {max_score}%")
print("\n2. Simulating the Real-World Effects:")
def calculate_score(hours):
    return 40 + 5*hours - 0.2*(hours**2)
hours_to_test = [5.0, 12.5, 15.0]
labels = [
    "Improving (Under 12.5 hours)",
    "Optimal Balance (Peak Score)",
    "Burnout / Fatigue (Past 12.5 hours)"
]
for hr, label in zip(hours_to_test, labels):
    score = calculate_score(hr)
    print(f"   * {hr:<4} hours -> Score: {score:.2f}% | Context: {label}")

import sympy as sp
x = sp.Symbol('x')
L = 5*x - 0.2*x**2
integral_val = sp.integrate(L, (x, 0, 5))
print("Fraction:", integral_val)
print("Decimal:", float(integral_val))

import sympy as sp
from scipy.integrate import quad
x = sp.Symbol('x')
L = 5*x - 0.2*x**2
F = sp.integrate(L, x)
print("Step 1: Antiderivative F(x) =")
sp.pprint(F)
F_5 = F.subs(x, 5)
F_0 = F.subs(x, 0)
print(f"\nStep 2.1: F(5) = {F_5}")
print(f"Step 2.2: F(0) = {F_0}")
exact_integral = sp.integrate(L, (x, 0, 5))
print(f"\nStep 3: Exact Definite Integral Value = {exact_integral}")
def L_func(hours):
    return 5 * hours - 0.2 * (hours ** 2)
numerical_integral, estimation_error = quad(L_func, 0, 5)
print(f"\nSciPy Numerical Decimal Approximation = {numerical_integral:.4f}")
print(f"Matches manual calculation (325/6)? {abs(numerical_integral - float(exact_integral)) < 1e-9}")

import numpy as np
from scipy.integrate import quad
def L(x):
    return 5 * x - 0.2 * x**2
n_intervals = 100000
x_vals = np.linspace(0, 5, n_intervals)
y_vals = L(x_vals)
dx = 5 / (n_intervals - 1)
trapezoidal_approx = dx * (0.5 * y_vals[0] + np.sum(y_vals[1:-1]) + 0.5 * y_vals[-1])
scipy_result, error_estimate = quad(L, 0, 5)
print(f"Manual Trapezoidal Approximation : {trapezoidal_approx:.4f}")
print(f"SciPy High-Precision Quadrature  : {scipy_result:.4f}")
print(f"Exact Analytical Fraction (325/6): {325/6:.4f}")

import sympy as sp

x = sp.symbols('x')


F = 40 + 5*x - 0.2*x*x
F_prime = sp.diff(F, x)


solutions = sp.solve(F_prime, x)

print("F'(x) =", F_prime)
print("Values of x:", solutions)

def F(x):
    return 40 + 5*x - 0.2*x**2
def dF(x):
    return 5 - 0.4*x
for x in range(1, 11):
    print(x, F(x), dF(x))
print("Maximum occurs at x =", 12.5)
print("Interpretation: 12.5 study hours gives the maximum value of F(x).")

result = (5 * 5**2 / 2) - (0.2 * 5**3 / 3)

print("Integral =", result)

import numpy as np

def L(x):
    return 5*x - 0.2*x**2

x = np.linspace(0, 5, 1000)

area = np.trapezoid(L(x), x)

print("Numerical approximation =", area)

area = 54.16666666666667

print("The area under the curve represents the total")
print("accumulated learning benefit from 0 to 5 study hours.")
print("Total accumulated learning benefit =", area)

import pandas as pd
data = {
    'Student': ['S1', 'S2', 'S3', 'S4','S5','S6','S7','S8','S9','S10'],
    'Study Hours': [2, 3, 4, 5, 6, 7, 8, 4, 6, 9],
    'Attendance': [65, 70, 75, 80, 85, 90, 92, 78, 88, 95],
    'Assignment_Score': [55,60,65,72,78,85,88,70,80,92],
    'Previous_Score': [58,62,68,70,76,82,86,72,79,90],
    'Final_Score': [60,64,70,75,82,88,91,74,84,94]
}
df = pd.DataFrame(data)
print("Study Hours vs Final Score:",
      df["Study Hours"].corr(df["Final_Score"]))

print("Attendance vs Final Score:",
      df["Attendance"].corr(df["Final_Score"]))

print("Assignment Score vs Final Score:",
      df["Assignment_Score"].corr(df["Final_Score"]))

print("Previous Score vs Final Score:",
      df["Previous_Score"].corr(df["Final_Score"]))

import numpy as np
import pandas as pd
data = {
    'Study Hours': [2, 3, 4, 5, 6, 7, 8, 4, 6, 9],
    'Attendance': [65, 70, 75, 80, 85, 90, 92, 78, 88, 95],
    'Assignment_Score': [55,60,65,72,78,85,88,70,80,92],
    'Final_Score': [60,64,70,75,82,88,91,74,84,94] # Added Final_Score
}
df = pd.DataFrame(data)

# Independent variables
X = df[["Study Hours", "Attendance", "Assignment_Score"]].values # Corrected column name

# Dependent variable
Y = df["Final_Score"].values

# Add a column of 1s for the intercept (b0)
X = np.column_stack((np.ones(len(X)), X))

# Calculate beta using:
# beta = (X^T X)^(-1) X^T Y
beta = np.linalg.inv(X.T @ X) @ X.T @ Y

print("Coefficients:")
print(beta)

# Display individual coefficients
print("b0 (Intercept) =", beta[0])
print("b1 (Study Hours) =", beta[1])
print("b2 (Attendance) =", beta[2])
print("b3 (Assignment Score) =", beta[3])

average = df["Final_Score"].mean()
print("Average Final Score:", average)

variation = df["Final_Score"].var()
std = df["Final_Score"].std()

print("Variance:", variation)
print("Standard Deviation:", std)

highest = df.loc[df["Final_Score"].idxmax()]

print("Student with highest final score:")
print(highest)

correlation = df["Study Hours"].corr(df["Final_Score"])

print("Study Hours vs Final Score:", correlation)

import numpy as np

X = df[["Study Hours", "Attendance", "Assignment_Score"]].values
Y = df["Final_Score"].values

X = np.column_stack((np.ones(len(X)), X))

print("Shape of X:", X.shape)
print("Shape of Y:", Y.shape)

import pandas as pd
data = {
    'Student': ['S1', 'S2', 'S3', 'S4','S5','S6','S7','S8','S9','S10'],
    'Study Hours': [2, 3, 4, 5, 6, 7, 8, 4, 6, 9],
    'Attendance': [65, 70, 75, 80, 85, 90, 92, 78, 88, 95],
    'Assignment_Score': [55,60,65,72,78,85,88,70,80,92],
    'Previous_Score': [58,62,68,70,76,82,86,72,79,90],
    'Final_Score': [60,64,70,75,82,88,91,74,84,94]
}
df = pd.DataFrame(data)
correlations = df[
    ["Study Hours", "Attendance", "Assignment_Score", "Previous_Score"]
].corrwith(df["Final_Score"])

print(correlations)

strongest = correlations.abs().idxmax()
print("Strongest correlation:", strongest)
print("Correlation value:", correlations[strongest])

def dF(x):
    return 5 - 0.4*x

print("Derivative at 5 hours:", dF(5))
print("Derivative at 10 hours:", dF(10))
print("Derivative at 12.5 hours:", dF(12.5))

import numpy as np

def L(x):
    return 5*x - 0.2*x**2

x = np.linspace(0, 5, 1000)
area = np.trapezoid(L(x), x)

print("Area under learning-benefit curve:", area)

print("Main Conclusions:")
print("1. The average final score represents the overall student performance.")
print("2. Variance and standard deviation show the spread of final scores.")
print("3. Correlation measures the linear relationship between study factors and final score.")
print("4. Study hours, attendance, assignment score, and previous score can be analyzed together using matrix regression.")
print("5. The derivative shows the marginal effect of additional study hours.")
print("6. The study-hours model reaches its maximum at 12.5 hours.")
print("7. The area under the learning-benefit curve from 0 to 5 hours is approximately 54.17.")