# -*- coding: utf-8 -*-
"""fifthday.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tMBFC1WOWP5ijPIbuQTY0uuG3PtiNDyc
"""

import pandas as pd
import numpy as np
s = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print("\nSeries:")
print(s)
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'Salary': [50000, 60000, 70000, 80000]
}
df = pd.DataFrame(data)
print("\nDataFrame:")
print(df)

array = np.array([[1, 2], [3, 4], [5, 6]])
df_from_array = pd.DataFrame(array, columns=['Column1', 'Column2'])
print("\nDataFrame from NumPy array:")
print(df_from_array)

print("\nRow with label 1 using loc:")
print(df.loc[1])

print("\nFirst two rows using iloc:")
print(df.iloc[0:2])

print("\nSelect 'Name' column:")
print(df['Name'])
print("\nSelect 'Name' and 'Age' columns:")
print(df[['Name', 'Age']])
print("\nRows where Salary > 60000:")
print(df[df['Salary'] > 60000])

data_dirty = {
    'Name': ['Alice', 'Bob', None, 'David'],
    'Age': [25, None, 35, 40],
    'Salary': [50000, 60000, None, 80000]
}
df_dirty = pd.DataFrame(data_dirty)
print("\nOriginal Dirty DataFrame:")
print(df_dirty)

print("\nDrop rows with any NaN values:")
print(df_dirty.dropna())
print("\nFill missing values with a specific value:")
print(df_dirty.fillna({'Name': 'Unknown', 'Age': df_dirty['Age'].mean(), 'Salary': 0}))

print("\nBoolean DataFrame for missing values:")
print(df_dirty.isnull())

df['Bonus'] = df['Salary'] * 0.1
print("\nDataFrame with Bonus column:")
print(df)
print("\nRename columns:")
df_renamed = df.rename(columns={'Salary': 'BaseSalary'})
print(df_renamed)
print("\nSort by Age descending:")
print(df.sort_values(by='Age', ascending=False))
print("\nGroup by operation (average salary by age > 30 or not):")
df['AgeGroup'] = df['Age'] > 30
print(df.groupby('AgeGroup')['Salary'].mean())

print("\nRename columns:")
df_renamed = df.rename(columns={'Salary': 'BaseSalary'})
print(df_renamed)

print("\nSort by Age descending:")
print(df.sort_values(by='Age', ascending=False))
print("\nGroup by operation (average salary by age > 30 or not):")
df['AgeGroup'] = df['Age'] > 30
print(df.groupby('AgeGroup')['Salary'].mean())

np.random.seed(1)
num_rows = 10
df_synth = pd.DataFrame({
    'ID': np.arange(1, num_rows + 1),
    'Score': np.random.randint(50, 100, size=num_rows),
    'Passed': np.random.choice([True, False], size=num_rows)
})

print("\nSynthetic DataFrame:")
print(df_synth)

print("\nStudents who passed:")
print(df_synth[df_synth['Passed'] == True])
print("\nAverage score of failed students:")
print(df_synth[df_synth['Passed'] == False]['Score'].mean())

print("\nDataFrame info:")
df.info()
print("\nDataFrame describe:")
print(df.describe())

print("\nData types of each column:")
print(df.dtypes)
print("\nFirst 3 rows:")
print(df.head(3))
print("\nLast 2 rows:")
print(df.tail(2))

print("\nMean Age:", df['Age'].mean())
print("Median Salary:", df['Salary'].median())
print("Mode of Bonus:")
print(df['Bonus'].mode())
print("Standard Deviation of Salary:", df['Salary'].std())
print("Variance of Salary:", df['Salary'].var())

print("\nCorrelation between Age and Salary:")
print(df[['Age', 'Salary']].corr())

print("\nCovariance between Age and Salary:")
print(df[['Age', 'Salary']].cov())


print("\nValue counts for AgeGroup:")
print(df['AgeGroup'].value_counts())

print("\nCumulative sum of Salary:")
print(df['Salary'].cumsum())

print("\nCumulative max of Salary:")
print(df['Salary'].cummax())


print("\nRank of Salary:")
print(df['Salary'].rank())


print("\nQuantiles of Salary:")
print(df['Salary'].quantile([0.25, 0.5, 0.75]))

