# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AyFjYVqqC5E2CQDwFl-74uHVE30aXEPi
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
np.random.seed(42)
print('Setup complete. NumPy', np.__version__)

rolls = np.random.randint(1, 7, size=100_000)
p_even = (rolls % 2 == 0).mean()
p_gt4  = (rolls > 4).mean()
print('P(even) ~', round(p_even, 3), ' (true 0.5)')
print('P(>4)   ~', round(p_gt4, 3),  ' (true 0.333)')

p_1 = (rolls == 1).mean()
p_2 = (rolls == 2).mean()
p_1_or_2 = (np.isin(rolls, [1, 2])).mean()
print('P(1) + P(2) =', round(p_1 + p_2, 3))
print('P(1 or 2)   =', round(p_1_or_2, 3), ' -> they match')

flips = np.random.randint(0, 2, size=(100_000, 2))
heads = flips.sum(axis=1)
p_both_heads = np.mean(heads == 2)
print("P(both heads):", p_both_heads)
p_at_least_one = np.mean(heads >= 1)
print("P(at least one head):", p_at_least_one)
p_0 = np.mean(heads == 0)
p_1 = np.mean(heads == 1)
p_2 = np.mean(heads == 2)
total = p_0 + p_1 + p_2
print("P(0) + P(1) + P(2):", total)
print("Does it sum to 1?", np.isclose(total, 1))

rolls = np.random.randint(1, 7, size=100_000)
even = rolls[rolls % 2 == 0]
p_6_given_even = (even == 6).mean()
print('P(6 | even) ~', round(p_6_given_even, 3), ' (true 1/3)')

A = rolls > 3
B = rolls % 2 == 0
p_A        = A.mean()
p_A_given_B = A[B].mean()
print('P(A)      =', round(p_A, 3))
print('P(A | B)  =', round(p_A_given_B, 3))
print('Independent?', np.isclose(p_A, p_A_given_B, atol=0.02))

rolls = np.random.randint(1, 7, size=100_000)
p_odd_given_less4 = np.mean(rolls[rolls < 4] % 2 == 1)
print("P(odd | roll < 4):", p_odd_given_less4)
p_less4 = np.mean(rolls < 4)
print("P(roll < 4):", p_less4)
p_odd = np.mean(rolls % 2 == 1)
print("P(odd):", p_odd)
print("Independent?", np.isclose(p_odd_given_less4, p_odd))

p_disease   = 0.01
p_pos_given_D  = 0.99
p_pos_given_nD = 0.01
p_pos = p_pos_given_D * p_disease + p_pos_given_nD * (1 - p_disease)
p_D_given_pos = (p_pos_given_D * p_disease) / p_pos
print('P(sick | positive test) =', round(p_D_given_pos, 3))
print('-> only ~50%, because the disease is rare (base-rate effect)')

N = 1_000_000
has_disease = np.random.rand(N) < p_disease
tests_pos = np.where(has_disease,
                     np.random.rand(N) < p_pos_given_D,
                     np.random.rand(N) < p_pos_given_nD)
among_positive = has_disease[tests_pos]
print('Simulated P(sick | positive) =', round(among_positive.mean(), 3))

p_spam = 0.20
p_free_given_spam = 0.60
p_free_given_ham  = 0.05
p_free = (p_free_given_spam * p_spam) + \
         (p_free_given_ham * (1 - p_spam))
print("P('free'):", p_free)
p_spam_given_free = (p_free_given_spam * p_spam) / p_free
print("P(spam | 'free'):", p_spam_given_free)

bern = stats.bernoulli(p=0.3).rvs(size=10_000)
print('Bernoulli(0.3) mean ~', round(bern.mean(), 3), '(true 0.3)')
pois = stats.poisson(mu=4).rvs(size=10_000)
print('Poisson(4) mean ~', round(pois.mean(), 3), '(true 4)')

x = np.linspace(-5, 5, 200)
fig, ax = plt.subplots(figsize=(7, 3.5))
for sigma in [0.5, 1.0, 2.0]:
    ax.plot(x, stats.norm(0, sigma).pdf(x), label=f'sigma={sigma}')
ax.set_title('Gaussian PDF for different spreads'); ax.legend(); plt.show()

import numpy as np
import matplotlib.pyplot as plt
samples = np.random.poisson(lam=2, size=10_000)
print("Sample mean:", np.mean(samples))
plt.hist(samples, bins=np.arange(-0.5, samples.max() + 1.5, 1),
         density=True, edgecolor="black")
plt.xlabel("Number of events")
plt.ylabel("Probability")
plt.title("Poisson Distribution (mu=2)")
plt.show()
mu = 0
x = np.linspace(-5, 5, 1000)
sigma1 = 1
sigma2 = 2
pdf1 = (1 / (sigma1 * np.sqrt(2 * np.pi))) * \
       np.exp(-0.5 * ((x - mu) / sigma1) ** 2)
pdf2 = (1 / (sigma2 * np.sqrt(2 * np.pi))) * \
       np.exp(-0.5 * ((x - mu) / sigma2) ** 2)
plt.plot(x, pdf1, label="sigma = 1")
plt.plot(x, pdf2, label="sigma = 2")
plt.xlabel("x")
plt.ylabel("Density")
plt.title("Gaussian PDFs with Different Spreads")
plt.legend()
plt.grid(alpha=0.3)
plt.show()

from scipy.stats import entropy
fair   = [0.5, 0.5]
biased = [0.9, 0.1]
certain= [1.0, 0.0]
print('Entropy fair coin   :', round(entropy(fair, base=2), 3), 'bits')
print('Entropy biased coin :', round(entropy(biased, base=2), 3), 'bits')
print('Entropy certain     :', round(entropy(certain, base=2), 3), 'bits')

P = np.array([0.5, 0.5])
Q = np.array([0.9, 0.1])
print('D(P || Q) =', round(entropy(P, Q, base=2), 3), 'bits')
print('D(P || P) =', round(entropy(P, P, base=2), 3), '-> zero (identical)')
print('Note: D(P||Q) != D(Q||P)  ->', round(entropy(Q, P, base=2), 3), '(not symmetric)')

from sklearn.feature_selection import mutual_info_classif
from sklearn.datasets import load_iris
iris = load_iris()
mi = mutual_info_classif(iris.data, iris.target, random_state=0)
for name, score in sorted(zip(iris.feature_names, mi), key=lambda t: -t[1]):
    print(f'{score:.3f}  {name}')
print('-> higher MI = the feature tells us more about the class')

import numpy as np
from scipy.stats import entropy
H4 = entropy([1/4] * 4, base=2)
H6 = entropy([1/6] * 6, base=2)
print("Entropy of 4-sided die:", H4, "bits")
print("Entropy of 6-sided die:", H6, "bits")
P = np.array([0.7, 0.3])
Q = np.array([0.5, 0.5])
D_PQ = entropy(P, Q, base=2)
print("KL divergence D(P || Q):", D_PQ, "bits")
print("Most informative: petal length")
print("Least informative: sepal width")