# -*- coding: utf-8 -*-
"""sixth day.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OH1IORoqvVHrJhSOPM_dPYw6VDeelq0e
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme(style='whitegrid')
np.random.seed(42)
df = sns.load_dataset('tips')
print('Loaded tips dataset:', df.shape)
df.head()

print(df.dtypes)
numerical   = df.select_dtypes(include='number').columns.tolist()
categorical = df.select_dtypes(exclude='number').columns.tolist()
print('\nNumerical  :', numerical)
print('Categorical:', categorical)

print('Mean total_bill:', round(df['total_bill'].mean(), 2))
print('Day value counts:')
print(df['day'].value_counts())

numerical_columns = df.select_dtypes(include='number').columns.tolist()
categorical_columns = df.select_dtypes(include='object').columns.tolist()
print("Numerical columns:")
print(numerical_columns)
print("\nCategorical columns:")
print(categorical_columns)
print("\nMean of tip:")
print(df['tip'].mean())
print("\nValue counts of sex:")
print(df['sex'].value_counts())

col = df['total_bill']
print('Mean   :', round(col.mean(), 2))
print('Median :', round(col.median(), 2))
print('Mode   :', round(col.mode()[0], 2))

print('mean > median ?', col.mean() > col.median(), '-> right-skewed')
plt.figure(figsize=(7, 3.5))
sns.histplot(col, kde=True)
plt.axvline(col.mean(),   color='red',   label='mean')
plt.axvline(col.median(), color='green', label='median')
plt.legend(); plt.title('total_bill: mean vs median'); plt.show()

import matplotlib.pyplot as plt
tip = df['tip']
mean_tip = tip.mean()
median_tip = tip.median()
mode_tip = tip.mode()[0]
print("Mean:", mean_tip)
print("Median:", median_tip)
print("Mode:", mode_tip)
if mean_tip > median_tip:
    print("The tip column is right-skewed based on mean > median.")
else:
    print("The tip column is not right-skewed based on mean > median.")
plt.figure(figsize=(8, 5))
plt.hist(tip, bins=15, edgecolor='black', alpha=0.7)
plt.axvline(mean_tip, color='red', linestyle='--', linewidth=2,
            label=f'Mean = {mean_tip:.2f}')
plt.axvline(median_tip, color='blue', linestyle='-', linewidth=2,
            label=f'Median = {median_tip:.2f}')
plt.xlabel('Tip')
plt.ylabel('Frequency')
plt.title('Distribution of Tips')
plt.legend()
plt.show()

col = df['total_bill']
print('Range :', round(col.max() - col.min(), 2))
print('Var   :', round(col.var(), 2))
print('Std   :', round(col.std(), 2))

q1, q3 = col.quantile(0.25), col.quantile(0.75)
iqr = q3 - q1
print('Q1 (25%):', round(q1, 2))
print('Q3 (75%):', round(q3, 2))
print('IQR     :', round(iqr, 2), '-> spread of the middle 50% (robust to outliers)')

tip = df['tip']
tip_range = tip.max() - tip.min()
tip_variance = tip.var()
tip_std = tip.std()
Q1 = tip.quantile(0.25)
Q3 = tip.quantile(0.75)
IQR = Q3 - Q1
print("Range:", tip_range)
print("Variance:", tip_variance)
print("Standard Deviation:", tip_std)
print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)

col = df['total_bill']
five = col.describe()[['min', '25%', '50%', '75%', 'max']]
print(five)
print('\nSkewness:', round(col.skew(), 3))

plt.figure(figsize=(7, 2.8))
sns.boxplot(x=df['total_bill'])
plt.title('Box plot of total_bill'); plt.show()

import matplotlib.pyplot as plt
tip = df['tip']
print("Five-number summary:")
print(tip.describe()[['min', '25%', '50%', '75%', 'max']])
skewness = tip.skew()
print("\nSkewness:", skewness)
plt.figure(figsize=(8, 4))
plt.boxplot(tip, vert=False)
plt.xlabel("Tip")
plt.title("Box Plot of Tip")
plt.show()

corr = df.corr(numeric_only=True)
print(corr.round(2))
print('\ntotal_bill vs tip:', round(corr.loc['total_bill', 'tip'], 2), '-> strong positive')

plt.figure(figsize=(5, 4))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='Blues', vmin=-1, vmax=1)
plt.title('Correlation matrix'); plt.show()

df.describe()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
correlation_matrix = df.corr(numeric_only=True).round(2)
print("Correlation Matrix:")
print(correlation_matrix)
plt.figure(figsize=(10, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title("Correlation Heatmap")
plt.show()
print("\nDescriptive Statistics:")
print(df.describe())